---
title: "Random Numbers"
author: "Aaron Palumbo"
date: "Saturday, May 30, 2015"
output: pdf_document
---

```{r}
library(ggplot2)

noise.param <- c(0, 10, 50)
n <- 100

df.list <- NULL
for(i  in 1:length(noise.param)){
  x <- 1:n
  noise <- runif(n, min=-1, max=1) * noise.param[i]
  y <- x + noise
  df.list[[i]] <- data.frame(x=x, y=y, noise=noise.param[i])
}

df.final <- do.call("rbind", df.list)

ggplot(data=df.final) + geom_point(aes(x, y)) + 
  ggtitle("Signal: x=y, Noise ~ Uniform") +
  geom_abline(intercept=0, slope=1, color='red') +
  facet_grid(. ~ noise) +
  ylim(c(-100, 200)) +
  theme_bw()
```

```{r}
noise.param <- c(0, 20, 40)
n <- 100

df.list <- NULL
for(i  in 1:length(noise.param)){
  x <- 1:n
  noise <- rnorm(n, mean=0, sd=noise.param[i])
  y <- x + noise
  df.list[[i]] <- data.frame(x=x, y=y, noise=noise.param[i])
}

df.final <- do.call("rbind", df.list)

ggplot(data=df.final) + geom_point(aes(x, y)) + 
  ggtitle("Signal: x=y, Noise ~ Normal") +
  geom_abline(intercept=0, slope=1, color='red') +
  facet_grid(. ~ noise) + 
  ylim(c(-100, 200)) +
  theme_bw()
```




supervised / unsupervised

```{r}
gen_data <- function(center, std, mix, points){
  rn1 <- rnorm(points)
  rn2 <- rnorm(points)
  
  rn1.factor <- mix[1]
  rn2.factor <- mix[2]
  
  corr1 <- rn1.factor * rn1 + rn2.factor * rn2
  corr1 <- scale(corr1)
  
  t1.m <- center[1]
  t1.sd <- std[1]
  t1 <- t1.sd * rn1 + t1.m
  
  t2.m <- center[2]
  t2.sd <- std[2]
  t2 <- corr1 * t2.sd + t2.m
  
  t.cor <- cor(t1, t2)
  
  df <- data.frame(test1=t1, test2=t2)
  
  return(df)
}

n <- 1000

c1 <- c(.8, .75)
c2 <- c(.6, .5)
c3 <- c(.8, .4)

std1 <- c(.05, .05)
std2 <- c(.1, .1)
std3 <- c(.03, .01)

mix1 <- c(1, 10)
mix2 <- c(3, 5)
mix3 <- c(2, 2)

clusters <- list()
clusters[[1]] <- list(c=c1, std=std1, mix=mix1)
clusters[[2]] <- list(c=c2, std=std2, mix=mix2)
clusters[[3]] <- list(c=c3, std=std3, mix=mix3)

groups <- c('red', 'green', 'blue')

df_list <- list()
for(i in 1:3){
  group.prob <- c(0.1, 0.1, 0.1)
  
  df <- gen_data(clusters[[i]]$c,
                 clusters[[i]]$std, 
                 clusters[[i]]$mix,
                 n)
  df['actual_grp'] <- i
  group.prob[i] <- 0.8
  df['grp'] <- sample(x = groups, size = n, replace = TRUE, prob = group.prob)
  df_list[[i]] <- df
}

df <- do.call("rbind", df_list)

ggplot(df) +
  geom_point(aes(x=test1, y=test2), 
             cex=2, alpha=.6) +
  scale_x_continuous(limits=c(0, 1), breaks=seq(0, 1, 0.1)) +
  scale_y_continuous(limits=c(0, 1), breaks=seq(0, 1, 0.1)) +
  xlab("Test One") + 
  ylab("Test Two") +
  ggtitle("Generated Data") +
  theme_bw() + theme(legend.position="none")

ggplot(df) +
  geom_point(aes(x=test1, y=test2, color=as.factor(actual_grp)), 
             cex=2, alpha=.6) +
  scale_x_continuous(limits=c(0, 1), breaks=seq(0, 1, 0.1)) +
  scale_y_continuous(limits=c(0, 1), breaks=seq(0, 1, 0.1)) +
  xlab("Test One") + 
  ylab("Test Two") +
  ggtitle("Generated Data") +
  theme_bw() + theme(legend.position="none")

```